<?php

namespace ReviewX;

\defined("ABSPATH") || exit;
return ['name' => 'ReviewX', 'slug' => 'reviewx', 'prefix' => 'rvx', 'rest_api_namespace' => 'reviewx', 'version' => '0.0.1', 'initial_handlers' => ['activated' => \ReviewX\Handlers\PluginActivatedHandler::class, 'deactivated' => \ReviewX\Handlers\PluginDeactivatedHandler::class, 'uninstalled' => [\ReviewX\Handlers\PluginUninstallerHandler::class, 'handleUninstall']], 'providers' => [\ReviewX\WPDrill\Providers\ShortcodeServiceProvider::class, \ReviewX\WPDrill\Providers\DBServiceProvider::class, \ReviewX\WPDrill\Providers\RequestServiceProvider::class, \ReviewX\WPDrill\Providers\MenuServiceProvider::class, \ReviewX\WPDrill\Providers\ViewServiceProvider::class, \ReviewX\WPDrill\Providers\ConfigServiceProvider::class, \ReviewX\WPDrill\Providers\EnqueueServiceProvider::class, \ReviewX\WPDrill\Providers\RoutingServiceProvider::class, \ReviewX\WPDrill\Providers\MigrationServiceProvider::class, \ReviewX\WPDrill\Providers\CommonServiceProvider::class, \ReviewX\Providers\PluginServiceProvider::class], 'build' => ['output_dir' => '.dist', 'commands' => ['before' => [], 'after' => [['composer', 'dump-autoload']]], 'cleanup' => [
    // 'composer.json',
    // 'composer.lock',
    'scoper.inc.php',
    '.editorconfig',
    '.gitignore',
    '.php-cs-fixer.cache',
    'package.json',
    'package-lock.json',
    'tests',
    '.env.dev',
    '.git',
    'node_modules',
    '.vscode',
    'frontend/.nx.cache',
    'frontend/.vscode',
    'frontend/apps',
    'frontend/libs',
    'frontend/locals',
    'frontend/node_modules',
    'frontend/.editorconfig',
    'frontend/.eslintignore',
    'frontend/.eslintrc.json',
    'frontend/.gitignore',
    'frontend/.prettierignore',
    'frontend/.prettierrc',
    'frontend/client-build.sh',
    'frontend/.prettierrc',
    'frontend/gettext-extract.js',
    'frontend/locals.js',
    'frontend/localsToJson.js',
    'frontend/nx.json',
    'frontend/package.json',
    'frontend/README.md',
    'frontend/reset.sh',
    'frontend/tsconfig.base.json',
    'frontend/vitest.workspace.ts',
    'frontend/yarn.lock',
    'frontend/dist/frontend.dist.libs.share-ui',
    "frontend/locals",
    "frontend/package-lock.json",
    "vendor/php-di/php-di/src/Compiler/Template.php",
    "storage/cache/views",
    "php-scoper",
    "build.sh",
    "nohup.out",
    "phpunit.xml",
    "reset-client.sh",
    "run_nohup.sh",
    "tunnel.sh",
    "wpdrill",
    "yarn.lock",
    'storage/cache/views/',
    'client-build.sh',
    'CHANGELOG.md',
    'cloudflared_tunnel.log',
]]];
